[modules]
log_file
#log_syslog
#log_tcp
#log_pgsql

#pptp
#l2tp
#sstp
pppoe
#ipoe

auth_mschap_v2
auth_mschap_v1
auth_chap_md5
auth_pap

#radius
chap-secrets

ippool

pppd_compat

#shaper
#net-snmp
#logwtmp
#connlimit

#ipv6_nd

[core]
log-level=5
#error-log=/var/log/accel-ppp.log

[log]
#syslog=accel-ppp
#syslog-facility=daemon
#copy=1
log-file=/var/log/accel-ppp.log
log-level=5
#log-tcp=127.0.0.1:3000

[pppoe]
interface=eth3
service-name=Zpot
#ac-name=Zpot

[dns]
dns1=192.168.20.1
dns2=8.8.8.8

[client-ip-range]
192.168.20.2-192.168.20.254

[ip-pool]
gw-ip-address=192.168.20.1

[ppp]
verbose=1
lcp-echo-interval=10
lcp-echo-failure=2
mtu=1492
mru=1492
noauth
#refuse-pap
#refuse-chap

[chap-secrets]
gw-ip-address=192.168.20.1
