use axum::{http::StatusCode, Json};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;
use std::fs;
use std::process::Command;

const SECRETS_JSON_PATH: &str = "/etc/zpot-ppp-secrets.json";

// P1: lock de secrets — serializa load-modify-save (sync 60s vs handlers)
// para que un borrado/reorden no se pierda ni "resucite"
static SECRETS_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct PppSecret {
    #[serde(default)]
    pub id: u32, // ID unico por cliente (1..n); reutiliza huecos al eliminar filas
    pub username: String,
    pub password: String,
    #[serde(default = "default_iface")]
    pub interface: String,
    #[serde(default = "default_ip")]
    pub ip: String,
    pub profile: String,
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub caller_id: String,
}

fn default_iface() -> String { "*".to_string() }
fn default_ip() -> String { "*".to_string() }

// Secrets — JSON + chap-secrets

/// Menor entero positivo no usado como id (reutiliza huecos al eliminar filas).
fn next_free_id(secrets: &[PppSecret]) -> u32 {
    let mut used: Vec<u32> = secrets.iter().map(|s| s.id).filter(|i| *i > 0).collect();
    used.sort_unstable();
    let mut candidate = 1u32;
    for u in used {
        if u == candidate { candidate += 1; }
        else if u > candidate { break; }
    }
    candidate
}

/// Asigna id a los secretos con id==0 usando el menor libre (en orden de
/// aparicion). Devuelve true si hubo cambios. Migra clientes viejos.
fn assign_missing_ids(secrets: &mut Vec<PppSecret>) -> bool {
    let mut used: Vec<u32> = secrets.iter().map(|s| s.id).filter(|i| *i > 0).collect();
    let mut changed = false;
    for s in secrets.iter_mut() {
        if s.id == 0 {
            let mut candidate = 1u32;
            while used.contains(&candidate) { candidate += 1; }
            s.id = candidate;
            used.push(candidate);
            changed = true;
        }
    }
    changed
}

fn load_secrets_json() -> Vec<PppSecret> {
    let mut secrets: Vec<PppSecret> = fs::read_to_string(SECRETS_JSON_PATH)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default();
    // Migracion: asignar id a clientes sin id (1..n en orden, reutiliza huecos)
    if assign_missing_ids(&mut secrets) {
        save_secrets_to_disk(&secrets);
        eprintln!("[PPP-SECRETS] ids asignados a {} clientes", secrets.len());
    }
    secrets
}

/// Persiste secrets JSON + regenera /etc/ppp/chap-secrets (fallback local).
/// FIX 2026-08-02: usado por el auto-registro desde la conexion PPP.
fn save_secrets_to_disk(secrets: &[PppSecret]) {
    // 1. JSON
    if let Some(parent) = std::path::Path::new(SECRETS_JSON_PATH).parent() {
        let _ = fs::create_dir_all(parent);
    }
    if let Ok(json) = serde_json::to_string_pretty(secrets) {
        // P1: escritura atomica (tmp+rename) — antes fs::write directo
        let tmp = format!("{}.tmp-{}", SECRETS_JSON_PATH, std::process::id());
        let _ = fs::write(&tmp, &json);
        let _ = fs::rename(&tmp, SECRETS_JSON_PATH);
    }
    // 2. chap-secrets (formato: client, server, secret, IP)
    let mut cs = String::from("# Generated by Zpot-RS\n");
    for s in secrets {
        if !s.enabled { continue; }
        // P1: NUNCA usar el username como password (auth local bypass).
        // Sin password local (auto-registro MSCHAPv2) → secret ALEATORIO
        // que no coincide con nada → la auth local falla para esos users
        // (correcto: no tienen password local; su auth es RADIUS).
        let secret = if s.password.is_empty() {
            let nanos = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.subsec_nanos())
                .unwrap_or(0);
            format!("zp-{:x}{:x}", std::process::id(), nanos)
        } else {
            s.password.clone()
        };
        let ip = if s.ip.is_empty() || s.ip == "*" { "*" } else { &s.ip };
        cs.push_str(&format!("{}\t*\t{}\t{}\n", s.username, secret, ip));
    }
    let _ = fs::write("/etc/ppp/chap-secrets", cs.as_bytes());
}

/// Auto-registro de cliente PPP desde la conexion (FIX 2026-08-02):
/// si el username NO existe en secrets JSON, se agrega con la IP que dio
/// el RADIUS (Framed-IP del Access-Accept). El password NO esta disponible
/// en la conexion (MSCHAPv2 solo transmite hash) -> queda vacio.
/// Si ya existe: solo se completa la IP si esta vacia o "*" (no se
/// sobreescriben IPs estaticas asignadas manualmente).
fn auto_register_from_connection(username: &str, client_ip: &str) -> bool {
    if username.is_empty() || client_ip.is_empty() { return false; }
    let _g = SECRETS_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let mut secrets = load_secrets_json();
    let exists = secrets.iter().any(|s| s.username.eq_ignore_ascii_case(username));
    if exists {
        // Completar IP solo si falta
        let mut changed = false;
        for s in secrets.iter_mut() {
            if s.username.eq_ignore_ascii_case(username) && (s.ip.is_empty() || s.ip == "*") {
                s.ip = client_ip.to_string();
                changed = true;
            }
        }
        if changed {
            save_secrets_to_disk(&secrets);
            eprintln!("[PPP-AUTOREG] {} IP completada a {}", username, client_ip);
            return true;
        }
        return false;
    }
    secrets.push(PppSecret {
        id: next_free_id(&secrets),
        username: username.to_string(),
        password: String::new(),
        interface: "*".to_string(),
        ip: client_ip.to_string(),
        profile: "ClientesPPP".to_string(),
        enabled: true,
        caller_id: String::new(),
    });
    save_secrets_to_disk(&secrets);
    eprintln!("[PPP-AUTOREG] Nuevo cliente agregado: {} ip={}", username, client_ip);
    true
}

pub async fn secrets_list() -> Result<Json<Vec<PppSecret>>, (StatusCode, String)> {
    // P2: enmascarar passwords — el SPA no necesita el password real
    // (ninguna pagina lo usa; evita exponer secretos en la UI)
    let mut secrets = load_secrets_json();
    for s in &mut secrets {
        if !s.password.is_empty() {
            s.password = "***".to_string();
        }
    }
    Ok(Json(secrets))
}

/// POST /api/ppp/secrets — crea o actualiza (upsert por username).
/// P2: antes NO existia API para crear/editar secretos (solo list/delete/
/// order/disconnect). El password "***" (enmascarado) conserva el actual.
pub async fn secrets_upsert(Json(mut body): Json<PppSecret>) -> Result<Json<serde_json::Value>, (StatusCode, String)> {
    let username = body.username.trim().to_string();
    if username.is_empty() {
        return Err((StatusCode::BAD_REQUEST, "username requerido".into()));
    }
    if username.chars().any(|c| c.is_control()) {
        return Err((StatusCode::BAD_REQUEST, "username con caracteres de control".into()));
    }
    if body.password == "***" {
        body.password.clear(); // conservar el actual (se rellena abajo)
    }
    if body.ip.is_empty() {
        body.ip = "*".to_string();
    }
    if !body.ip.is_empty() && body.ip != "*" && body.ip.parse::<std::net::Ipv4Addr>().is_err() {
        return Err((StatusCode::BAD_REQUEST, format!("ip invalida: {}", body.ip)));
    }

    let _g = SECRETS_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let mut secrets = load_secrets_json();
    let existing = secrets.iter_mut().find(|s| s.username.eq_ignore_ascii_case(&username));
    match existing {
        Some(s) => {
            // conservar el password actual si el body no trae uno nuevo
            if body.password.is_empty() {
                body.password = s.password.clone();
            }
            *s = body;
            s.username = username.clone();
        }
        None => {
            let id = next_free_id(&secrets);
            body.id = id;
            body.username = username.clone();
            secrets.push(body);
        }
    }
    save_secrets_to_disk(&secrets);
    Ok(Json(serde_json::json!({"ok": true, "username": username})))
}

async fn disconnect_user(username: &str) -> Result<String, String> {
    // Correlacion SIN depender del syslog (se pierde con rotacion):
    //   username -> IP (secrets JSON)
    //   IP -> interfaz pppN (ip -json addr, campo "address" = peer)
    //   pppN -> MAC (/var/run/ppp-mac-pppN) -> pppd PID (remotenumber)
    // OJO: el comando viejo usaba `pkill -f '^pppd'` = mataba TODOS los pppd.
    let secrets = load_secrets_json();
    let Some(ip) = secrets.iter()
        .find(|s| s.username.eq_ignore_ascii_case(username))
        .and_then(|s| if s.ip.is_empty() || s.ip == "*" { None } else { Some(s.ip.clone()) })
    else { return Ok(String::new()); };

    let out = tokio::process::Command::new("/bin/sh")
        .args(["-c", "ip -json addr show type ppp 2>/dev/null || echo '[]'"])
        .output().await.ok();
    let Some(out) = out else { return Ok(String::new()); };
    let links: Vec<serde_json::Value> = serde_json::from_slice(&out.stdout).unwrap_or_default();
    let mut intf = String::new();
    for link in &links {
        let peer = link["addr_info"].as_array()
            .and_then(|a| a.get(0))
            .and_then(|a| a["address"].as_str())
            .unwrap_or("");
        if peer == ip {
            if let Some(n) = link["ifname"].as_str() {
                intf = n.to_string();
            }
        }
    }
    if intf.is_empty() { return Ok(String::new()); }

    // Matar SOLO el pppd de esa interfaz (por MAC del peer en su cmdline)
    // OJO: /proc/PID/cmdline separa args con \0 -> convertir a espacios antes
    // de grep (mismo truco que el ip-up). Raw string: sin escapes Rust.
    let kill_cmd = format!(r#"mac=$(cat /var/run/ppp-mac-{intf} 2>/dev/null | tr -d ' \n'); [ -z "$mac" ] && exit 1; for pid in $(pgrep -x pppd 2>/dev/null); do if grep -q "remotenumber $mac" <(tr '\0' ' ' < /proc/$pid/cmdline) 2>/dev/null; then kill $pid 2>/dev/null; exit 0; fi; done; exit 1"#);
    // P1: verificar el RESULTADO del kill — antes `let _` ignoraba el fallo
    // y respondia "disconnected" aunque el pppd siguiera vivo (falso exito)
    let kill_out = tokio::process::Command::new("/bin/sh").args(["-c", &kill_cmd]).output().await
        .map_err(|e| e.to_string())?;
    if !kill_out.status.success() {
        return Err(format!("no se pudo matar el pppd de {}", intf));
    }
    Ok(intf)
}

pub async fn secrets_disconnect(Json(body): Json<serde_json::Value>) -> Result<Json<serde_json::Value>, (StatusCode, String)> {
    let username = body["username"].as_str().ok_or((StatusCode::BAD_REQUEST, "username required".to_string()))?;
    match disconnect_user(username).await {
        Ok(intf) if intf.is_empty() => Ok(Json(serde_json::json!({"ok": true, "message": "no active session"}))),
        Ok(intf) => Ok(Json(serde_json::json!({"ok": true, "disconnected": intf}))),
        Err(e) => Err((StatusCode::BAD_REQUEST, e)),
    }
}

/// POST /api/ppp/secrets/delete — elimina un secreto del JSON (y regenera
/// chap-secrets). El id queda LIBRE: el proximo cliente sin registro (o el
/// sync) lo reutiliza via next_free_id.
pub async fn secrets_delete(Json(body): Json<serde_json::Value>) -> Json<serde_json::Value> {
    let username = body["username"].as_str().unwrap_or("").trim().to_string();
    if username.is_empty() {
        return Json(serde_json::json!({"ok": false, "error": "username required"}));
    }
    let _g = SECRETS_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let mut secrets = load_secrets_json();
    let before = secrets.len();
    secrets.retain(|s| !s.username.eq_ignore_ascii_case(&username));
    if secrets.len() == before {
        return Json(serde_json::json!({"ok": true, "message": "no existe"}));
    }
    save_secrets_to_disk(&secrets);
    eprintln!("[PPP-SECRETS] eliminado {} (quedan {})", username, secrets.len());
    Json(serde_json::json!({"ok": true, "deleted": username, "remaining": secrets.len()}))
}

/// POST /api/ppp/secrets/order — reordena el JSON segun el array de
/// usernames recibido (drag & drop de la UI). No toca los ids.
pub async fn secrets_order(Json(body): Json<serde_json::Value>) -> Json<serde_json::Value> {
    let order: Vec<String> = body["order"].as_array()
        .map(|a| a.iter().filter_map(|v| v.as_str().map(|s| s.to_string())).collect())
        .unwrap_or_default();
    if order.is_empty() {
        return Json(serde_json::json!({"ok": false, "error": "order required"}));
    }
    let _g = SECRETS_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    let mut secrets = load_secrets_json();
    let mut ordered: Vec<PppSecret> = Vec::with_capacity(secrets.len());
    for name in &order {
        if let Some(pos) = secrets.iter().position(|s| s.username.eq_ignore_ascii_case(name)) {
            ordered.push(secrets.remove(pos));
        }
    }
    ordered.extend(secrets); // los que no estaban en el order (nuevos) al final
    save_secrets_to_disk(&ordered);
    eprintln!("[PPP-SECRETS] orden actualizado ({} filas)", ordered.len());
    Json(serde_json::json!({"ok": true, "count": ordered.len()}))
}

// Active sessions

/// Resultado del parse del syslog: correlacion intf->usuario y IP->usuario.
/// La IP es mas confiable (el intf pppN se recicla entre reconexiones).
struct SyslogUsers {
    by_intf: std::collections::HashMap<String, String>,
    by_ip: std::collections::HashMap<String, String>,
}

/// Parsea el syslog de pppd: lineas "user X logged in intf pppN ... remote
/// <IP>" -> mapas intf->usuario y IP->usuario.
/// FIX 2026-08-02: lee TAMBIEN /var/log/messages.0 (rotado) — el syslog rota
/// y los clientes conectados desde antes de la rotacion solo tienen su linea
/// en el archivo viejo. El orden messages.0 -> messages hace que las lineas
/// nuevas sobreescriban las viejas del mismo intf/IP.
fn parse_syslog_users() -> SyslogUsers {
    let mut by_intf = std::collections::HashMap::new();
    let mut by_ip = std::collections::HashMap::new();
    for path in ["/var/log/messages.0", "/var/log/messages"] {
        let log_data = std::fs::read_to_string(path).unwrap_or_default();
        for line in log_data.lines() {
            if let Some(idx) = line.find(" logged in ") {
                let before = &line[..idx];
                let mut user = String::new();
                if let Some(user_pos) = before.rfind("user ") {
                    let user_start = user_pos + 5;
                    let user_end = before[user_start..].find(' ').map(|p| user_start + p).unwrap_or(before.len());
                    user = before[user_start..user_end].trim().to_string();
                }
                let mut intf = String::new();
                if let Some(intf_pos) = line[idx..].find("intf ") {
                    let intf_start = idx + intf_pos + 5;
                    let intf_end = line[intf_start..].find(' ').map(|p| intf_start + p).unwrap_or(line.len());
                    intf = line[intf_start..intf_end].trim().to_string();
                }
                let mut ip = String::new();
                if let Some(rem_pos) = line[idx..].find("remote ") {
                    let rem_start = idx + rem_pos + 7;
                    let rem_end = line[rem_start..].find(' ').map(|p| rem_start + p).unwrap_or(line.len());
                    ip = line[rem_start..rem_end].trim().to_string();
                }
                if !user.is_empty() {
                    if !intf.is_empty() { by_intf.insert(intf, user.clone()); }
                    if !ip.is_empty() { by_ip.insert(ip, user); }
                }
            }
        }
    }
    SyslogUsers { by_intf, by_ip }
}

/// Fetch interfaces PPP vivas del kernel (ip -json addr show type ppp).
async fn fetch_ppp_links() -> Vec<serde_json::Value> {
    tokio::process::Command::new("/bin/sh")
        .args(["-c", "ip -json addr show type ppp 2>/dev/null || echo '[]'"])
        .output()
        .await
        .map(|o| serde_json::from_slice(&o.stdout).unwrap_or_default())
        .unwrap_or_default()
}

/// Sync periodico: syslog + kernel -> auto-registro de /ppp/secrets.
/// NO depende del ip-up: si el POST del ip-up fallo (backend caido), este
/// task lo captura en <=60s. Idempotente (auto_register no duplica ni
/// sobreescribe IPs fijas). Misma fuente que active_list.
async fn ppp_sync_once() {
    let log_map = parse_syslog_users();
    let links = fetch_ppp_links().await;
    let mut checked = 0usize;
    let mut changed = 0usize;
    for link in &links {
        let ifname = link["ifname"].as_str().unwrap_or("");
        let peer = link["addr_info"].as_array()
            .and_then(|a| a.get(0))
            .and_then(|a| a["address"].as_str())
            .unwrap_or("");
        if ifname.is_empty() || peer.is_empty() { continue; }
        // Prioridad por IP (estable por sesion), fallback por intf
        let user = log_map.by_ip.get(peer).cloned()
            .or_else(|| log_map.by_intf.get(ifname).cloned())
            .unwrap_or_default();
        if user.is_empty() { continue; }
        checked += 1;
        if auto_register_from_connection(&user, peer) { changed += 1; }
    }
    if changed > 0 {
        eprintln!("[PPP-SYNC] revisadas {} sesiones activas, {} cambios en secrets", checked, changed);
    }
}

/// Spawnea el sync periodico de clientes PPP (cada 60s, primero inmediato).
pub fn spawn_ppp_sync_task() {
    tokio::spawn(async {
        use tokio::time::{interval, Duration};
        let mut tick = interval(Duration::from_secs(60));
        loop {
            tick.tick().await;
            ppp_sync_once().await;
        }
    });
}

pub async fn active_list() -> Result<Json<Vec<serde_json::Value>>, (StatusCode, String)> {
    // Usar ip -json addr para obtener peer IP (remote)
    let links = fetch_ppp_links().await;

    // Build peer_ip -> username map from chap-secrets JSON
    let secrets: Vec<PppSecret> = fs::read_to_string(SECRETS_JSON_PATH)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default();
    let mut ip_to_user = std::collections::HashMap::new();
    for s in &secrets {
        if s.enabled && !s.ip.is_empty() && s.ip != "*" {
            ip_to_user.insert(s.ip.clone(), s.username.clone());
        }
    }

    // Get username per ppp interface from /var/log/messages
    let log_map = parse_syslog_users();

    let mut sessions = Vec::new();

    // Leer estadisticas reales del kernel (rx/tx bytes)
    let stats_raw = tokio::process::Command::new("/bin/sh")
        .args(["-c", "ip -j -s link show type ppp 2>/dev/null || echo '[]'"])
        .output()
        .await
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;
    let stats_links: Vec<serde_json::Value> = serde_json::from_slice(&stats_raw.stdout)
        .unwrap_or_default();
    let mut stats_map = std::collections::HashMap::new();
    for link in &stats_links {
        let name = link["ifname"].as_str().unwrap_or("").to_string();
        if name.is_empty() { continue; }
        let rx_b = link["stats64"]["rx"]["bytes"].as_u64().unwrap_or(0);
        let tx_b = link["stats64"]["tx"]["bytes"].as_u64().unwrap_or(0);
        stats_map.insert(name, (rx_b, tx_b));
    }

    // UPTIME ELIMINADO (2026-08-08): ppp_uptime ejecutaba 3 comandos sync
    // por interfaz (pgrep+awk+awk = 7 procesos) → ~235 procesos por
    // llamada con 33 PPP. El operador solo necesita conectado/desconectado.
    // /api/ppp/active baja de ~330ms a ~15ms.

    for link in &links {
        let ifname = link["ifname"].as_str().unwrap_or("");
        if ifname.is_empty() { continue; }
        let (bytes_in, bytes_out) = stats_map.get(ifname).copied().unwrap_or((0, 0));

        // Syslog (por IP primero — estable — luego por intf), despues
        // fallback a chap-secrets JSON por IP
        let peer_ip = link["addr_info"].as_array()
            .and_then(|a| a.get(0))
            .and_then(|a| a["address"].as_str())
            .unwrap_or("")
            .to_string();
        let mut user = log_map.by_ip.get(&peer_ip).cloned()
            .or_else(|| log_map.by_intf.get(ifname).cloned())
            .unwrap_or_else(|| "-".to_string());

        if user == "-" && !peer_ip.is_empty() {
            user = ip_to_user.get(&peer_ip).cloned().unwrap_or_else(|| "-".to_string());
        }

        sessions.push(serde_json::json!({
            "interface": ifname,
            "user": user,
            "remote_ip": peer_ip,
            "local_ip": link["addr_info"].as_array().and_then(|a| a.get(0)).and_then(|a| a["local"].as_str()).unwrap_or("-"),
            "bytes_in": bytes_in,
            "bytes_out": bytes_out,
        }));
    }
    Ok(Json(sessions))
}

// Logs
pub async fn logs_list() -> Result<Json<Vec<serde_json::Value>>, (StatusCode, String)> {
    let output = tokio::process::Command::new("/bin/sh")
        .args(["-c", "journalctl -u ppp --no-pager -n 50 2>/dev/null || grep -i -E '(ppp|pppoe|pppd)' /var/log/messages 2>/dev/null | tail -50 || echo 'no logs'"])
        .output()
        .await
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))?;

    let text = String::from_utf8_lossy(&output.stdout);
    let mut logs = Vec::new();
    for line in text.lines().rev().take(50) {
        if line.is_empty() { continue; }
        logs.push(serde_json::json!({"line": line}));
    }
    Ok(Json(logs))
}

// ─── QoS para PPPoE ──────────────────────────────────────────

fn to_kbps(s: &str) -> u64 {
    let s = s.trim().to_uppercase();
    if s.ends_with("M") {
        let n: f64 = s.trim_end_matches("M").parse().unwrap_or(0.0);
        (n * 1000.0) as u64
    } else if s.ends_with("K") {
        let n: f64 = s.trim_end_matches("K").parse().unwrap_or(0.0);
        n as u64
    } else {
        s.parse().unwrap_or(0)
    }
}

fn ip_to_minors(ip: &str) -> (u16, u16) {
    let last: u16 = ip.rsplit('.').next()
        .and_then(|s| s.parse().ok())
        .unwrap_or(1);
    (1000 + last * 2, 1000 + last * 2 + 1)
}

/// Aplica QoS en interfaz PPP — usa pppN (IP puro, sin encapsulación)
/// DOWN en egress de pppN (trafico server→cliente), UP en egress de ifb_pppN (trafico cliente→server via ingress redirect)
/// FIX 2026-08-02: rate (garantizado) y ceil (máximo) SEPARADOS del VSA
/// "rate_up/rate_down ceil_up/ceil_down". Antes el ceil se usaba como rate
/// (clase rate==ceil) — ahora se respeta exactamente lo del RADIUS.
fn apply_qos_ppp(client_ip: &str, ppp_iface: &str, speed_up: &str, speed_down: &str, up_ceil_str: &str, down_ceil_str: &str) {
    // NOTA: El QoS se aplica POR CLIENTE en su interfaz pppN individual.
    // NO limitar en WAN (eth0/eth1/eth2) porque hay balanceo de carga
    // (MWAN activo). Cada cliente PPP tiene su propio arbol HTB en pppN
    // (DOWN egress) y su propio ifb_pppN (UP via ingress redirect).
    // Esto funciona independientemente de por que WAN salga el trafico.
    if speed_up.is_empty() || speed_down.is_empty() { return; }
    let up_kbps = to_kbps(speed_up);
    let down_kbps = to_kbps(speed_down);
    if up_kbps == 0 && down_kbps == 0 { return; }
    // Ceil (máximo): si el RADIUS lo manda se usa; sino ceil = rate
    let up_ceil_kbps = if up_ceil_str.is_empty() { up_kbps } else { to_kbps(up_ceil_str) };
    let down_ceil_kbps = if down_ceil_str.is_empty() { down_kbps } else { to_kbps(down_ceil_str) };

    eprintln!("[PPP-QOS] {client_ip}@{ppp_iface}: up={speed_up}({up_kbps}kbps/ceil={up_ceil_kbps}kbps) down={speed_down}({down_kbps}kbps/ceil={down_ceil_kbps}kbps)");

    let (down_min, up_min) = ip_to_minors(client_ip);
    let down_cid = format!("1:{down_min}");
    let up_cid = format!("1:{up_min}");
    let ifb_name = format!("ifb_{ppp_iface}");

    // Limpiar estado previo en pppN (DOWN) y en ifb (UP)
    // PRIO UNICO POR CLIENTE (100+last_octet): con prio 1 compartido el del
    // operaba sobre el primer filtro del bucket, que podia ser de otro cliente.
    let prio = format!("{}", 100 + (down_min - 1000) / 2);
    let _ = Command::new("tc").args(["filter", "del", "dev", ppp_iface, "parent", "1:0", "protocol", "ip", "prio", &prio,
        "u32", "match", "ip", "dst", client_ip, "flowid", &down_cid]).output();
    let _ = Command::new("tc").args(["class", "del", "dev", ppp_iface, "classid", &down_cid]).output();

    let _ = Command::new("tc").args(["filter", "del", "dev", &ifb_name, "parent", "1:0", "protocol", "ip", "prio", &prio,
        "u32", "match", "ip", "src", client_ip, "flowid", &up_cid]).output();
    let _ = Command::new("tc").args(["class", "del", "dev", &ifb_name, "classid", &up_cid]).output();

    // Garantizar arbol HTB root en pppN con default class
    let out = Command::new("tc").args(["class", "show", "dev", ppp_iface, "classid", "1:1"]).output();
    let has_class1 = out.map(|o| String::from_utf8_lossy(&o.stdout).contains("htb")).unwrap_or(false);
    if !has_class1 {
        let _ = Command::new("tc").args(["qdisc", "add", "dev", ppp_iface, "root", "handle", "1:", "htb", "default", "2"]).output();
        let _ = Command::new("tc").args(["class", "add", "dev", ppp_iface, "parent", "1:", "classid", "1:1", "htb", "rate", "100mbit"]).output();
        let _ = Command::new("tc").args(["class", "add", "dev", ppp_iface, "parent", "1:1", "classid", "1:2", "htb", "rate", "100mbit", "ceil", "100mbit", "burst", "64k", "cburst", "64k"]).output();
    }

    // Preparar ifb_pppN para UP (crear si no existe, levantar, luego construir arbol HTB)
    let _ = Command::new("ip").args(["link", "add", &ifb_name, "type", "ifb"]).output();
    let _ = Command::new("ip").args(["link", "set", &ifb_name, "up"]).output();
    // rp_filter=2 (loose) necesario porque IFB no participa en tabla de ruteo
    let _ = Command::new("sysctl").args(["-w", &format!("net.ipv4.conf.{}.rp_filter=2", &ifb_name)]).output();
    let _ = Command::new("sysctl").args(["-w", &format!("net.ipv4.conf.{}.rp_filter=2", ppp_iface)]).output();

    // Garantizar arbol HTB root en ifb_pppN para UP (trafico cliente→server)
    let out2 = Command::new("tc").args(["class", "show", "dev", &ifb_name, "classid", "1:1"]).output();
    let has_ifb_htb = out2.map(|o| String::from_utf8_lossy(&o.stdout).contains("htb")).unwrap_or(false);
    if !has_ifb_htb {
        let _ = Command::new("tc").args(["qdisc", "add", "dev", &ifb_name, "root", "handle", "1:", "htb", "default", "2"]).output();
        let _ = Command::new("tc").args(["class", "add", "dev", &ifb_name, "parent", "1:", "classid", "1:1", "htb", "rate", "100mbit"]).output();
        let _ = Command::new("tc").args(["class", "add", "dev", &ifb_name, "parent", "1:1", "classid", "1:2", "htb", "rate", "100mbit", "ceil", "100mbit", "burst", "64k", "cburst", "64k"]).output();
    }

    // Garantizar ingress qdisc + redirect en pppN hacia ifb_pppN
    let has_ingress = Command::new("tc").args(["qdisc", "show", "dev", ppp_iface, "parent", "ffff:"]).output()
        .map(|o| String::from_utf8_lossy(&o.stdout).contains("ingress")).unwrap_or(false);
    if !has_ingress {
        let _ = Command::new("tc").args(["qdisc", "add", "dev", ppp_iface, "ingress"]).output();
    }

    // Redirigir ingress de pppN a ifb_pppN (solo si no existe ya)
    let has_redirect = Command::new("tc").args(["filter", "show", "dev", ppp_iface, "parent", "ffff:"]).output()
        .map(|o| String::from_utf8_lossy(&o.stdout).contains(&ifb_name)).unwrap_or(false);
    if !has_redirect {
        let _ = Command::new("tc").args(["filter", "add", "dev", ppp_iface, "parent", "ffff:", "protocol", "all",
            "u32", "match", "u32", "0", "0", "action", "mirred", "egress", "redirect", "dev", &ifb_name]).output();
    }

    // Burst proporcional: 100ms de datos para buena performance TCP
    let down_burst = format!("{}b", std::cmp::min(std::cmp::max(down_kbps * 125, 16000), 131072));
    let up_burst = format!("{}b", std::cmp::min(std::cmp::max(up_kbps * 125, 16000), 131072));

    let down_ceil = std::cmp::min(down_ceil_kbps, 100000);
    let up_ceil = std::cmp::min(up_ceil_kbps, 100000);

    // Clase DOWN en pppN egress (match dst IP = servidor→cliente)
    if down_kbps > 0 {
        let changed = Command::new("tc").args(["class", "change", "dev", ppp_iface, "classid", &down_cid, "htb",
            "rate", &format!("{}kbit", down_kbps), "ceil", &format!("{}kbit", down_ceil),
            "burst", &down_burst, "cburst", &down_burst]).output()
            .map(|o| o.status.success()).unwrap_or(false);
        if !changed {
            let _ = Command::new("tc").args(["class", "add", "dev", ppp_iface, "parent", "1:1", "classid", &down_cid, "htb",
                "rate", &format!("{}kbit", down_kbps), "ceil", &format!("{}kbit", down_ceil),
                "burst", &down_burst, "cburst", &down_burst]).output();
        }
        let _ = Command::new("tc").args(["filter", "add", "dev", ppp_iface, "parent", "1:0", "protocol", "ip", "prio", &prio,
            "u32", "match", "ip", "dst", client_ip, "flowid", &down_cid]).output();
    }

    // Clase UP en ifb_pppN egress (match src IP = cliente→servidor via ingress redirect)
    if up_kbps > 0 {
        let changed = Command::new("tc").args(["class", "change", "dev", &ifb_name, "classid", &up_cid, "htb",
            "rate", &format!("{}kbit", up_kbps), "ceil", &format!("{}kbit", up_ceil),
            "burst", &up_burst, "cburst", &up_burst]).output()
            .map(|o| o.status.success()).unwrap_or(false);
        if !changed {
            let _ = Command::new("tc").args(["class", "add", "dev", &ifb_name, "parent", "1:1", "classid", &up_cid, "htb",
                "rate", &format!("{}kbit", up_kbps), "ceil", &format!("{}kbit", up_ceil),
                "burst", &up_burst, "cburst", &up_burst]).output();
        }
        let _ = Command::new("tc").args(["filter", "add", "dev", &ifb_name, "parent", "1:0", "protocol", "ip", "prio", &prio,
            "u32", "match", "ip", "src", client_ip, "flowid", &up_cid]).output();
    }
}

/// POST /api/ppp/qos/radius — llamado por ip-up cuando RADIUS está activo.
/// Lee /var/run/radattr.pppN (escrito por radattr.so) y extrae la VSA MikroTik
/// rate-limit (oui 14988, vt 8/53) con el MISMO formato que hotspot:
/// "rate_up/rate_down ceil_up/ceil_down" → aplica QoS tc.
pub async fn qos_radius_apply(Json(body): Json<HashMap<String, String>>) -> Result<Json<Value>, (StatusCode, String)> {
    let username = body.get("username").cloned().unwrap_or_default();
    let client_ip = body.get("ip").cloned().unwrap_or_default();
    let ppp_iface = body.get("iface").cloned().unwrap_or_default();
    if client_ip.is_empty() || ppp_iface.is_empty() {
        return Err((StatusCode::BAD_REQUEST, "ip and iface required".into()));
    }

    let radattr_path = format!("/var/run/radattr.{ppp_iface}");
    let radattr = std::fs::read_to_string(&radattr_path).unwrap_or_default();

    // Auto-registro del cliente desde la conexion (FIX 2026-08-02):
    // si el username no existe en secrets JSON se agrega con la IP del RADIUS
    auto_register_from_connection(&username, &client_ip);

    // Buscar linea "26:<hex>" (Vendor-Specific) o nombre directo
    // "Mikrotik-Rate-Limit <valor>" — radattr.so escribe las VSAs que
    // CONOCE por nombre (dictionary de radiusclient): los MS-MPPE se ven
    // como "MS-MPPE-Recv-Key ..."; con Mikrotik en el dictionary la VSA
    // llega como "Mikrotik-Rate-Limit 1M/4M 2M/5M". El "26:<hex>" queda
    // como fallback para diccionarios que no la conocen.
    let mut raw_rate: Option<String> = None;
    for line in radattr.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("Mikrotik-Rate-Limit") {
            let v = rest.trim();
            if !v.is_empty() {
                raw_rate = Some(v.to_string());
                break;
            }
        }
        if !line.starts_with("26:") { continue; }
        let hexpart = line[3..].trim();
        // radattr escribe el value completo del attr 26 como hex:
        // vendor-id(4) + vendor-type(1) + vendor-len(1) + data
        let bytes = hex_to_bytes(hexpart);
        if bytes.len() >= 6 {
            let oui = u32::from_be_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]);
            if oui == 14988 {
                let vt = bytes[4];
                let vl = bytes[5] as usize;
                if (vt == 8 || vt == 53) && 6 + vl <= bytes.len() {
                    if let Ok(s) = std::str::from_utf8(&bytes[6..6 + vl]) {
                        raw_rate = Some(s.trim().to_string());
                        break;
                    }
                }
            }
        }
    }

    let Some(raw) = raw_rate else {
        // Sin VSA rate-limit: solo RADIUS (perfiles locales eliminados) -> sin QoS
        return Ok(Json(serde_json::json!({"status": "ok", "qos": "no rate-limit in radattr"})));
    };

    // Parse formato Zpot: "rate_up/rate_down ceil_up/ceil_down"
    let tokens: Vec<&str> = raw.split_whitespace().collect();
    let (mut speed_up, mut speed_down, mut up_ceil, mut down_ceil) = (String::new(), String::new(), String::new(), String::new());
    if let Some(t0) = tokens.first() {
        if t0.contains('/') {
            let p: Vec<&str> = t0.split('/').collect();
            speed_up = p[0].to_string();
            if p.len() >= 2 { speed_down = p[1].to_string(); }
            if tokens.len() >= 2 {
                let c: Vec<&str> = tokens[1].split('/').collect();
                up_ceil = c[0].to_string();
                if c.len() >= 2 { down_ceil = c[1].to_string(); }
            }
        } else {
            speed_up = t0.to_string();
            if tokens.len() >= 2 { speed_down = tokens[1].to_string(); }
        }
    }

    if speed_up.is_empty() && speed_down.is_empty() {
        return Ok(Json(serde_json::json!({"status": "ok", "qos": "empty rate-limit"})));
    }

    eprintln!("[PPP-RADIUS-QOS] {username}@{ppp_iface} ip={client_ip} raw={raw} -> up={speed_up} down={speed_down} ceil_up={up_ceil} ceil_down={down_ceil}");

    // Aplicar QoS con rate y ceil separados (transparente: respeta el VSA)
    apply_qos_ppp(&client_ip, &ppp_iface, &speed_up, &speed_down, &up_ceil, &down_ceil);

    Ok(Json(serde_json::json!({
        "status": "ok", "qos": "applied-radius", "raw": raw,
        "speed_up": speed_up, "speed_down": speed_down,
        "ceil_up": up_ceil, "ceil_down": down_ceil,
    })))
}

/// POST /api/ppp/qos/cleanup — llamado por ip-down al desconectarse.
/// Limpia clases/filtros tc de la interfaz (best-effort; ip-down ademas
/// elimina la interfaz con ip link delete, lo que borra su arbol tc).
pub async fn qos_cleanup(Json(body): Json<HashMap<String, String>>) -> Json<Value> {
    let client_ip = body.get("ip").cloned().unwrap_or_default();
    let ppp_iface = body.get("iface").cloned().unwrap_or_default();
    if client_ip.is_empty() || ppp_iface.is_empty() {
        return Json(serde_json::json!({"ok": true, "cleanup": "no-op"}));
    }
    let (down_min, up_min) = ip_to_minors(&client_ip);
    let prio = format!("{}", 100 + (down_min - 1000) / 2);
    let _ = Command::new("tc").args(["filter", "del", "dev", &ppp_iface, "parent", "1:0", "protocol", "ip", "prio", &prio,
        "u32", "match", "ip", "dst", &client_ip, "flowid", &format!("1:{down_min}")]).output();
    let _ = Command::new("tc").args(["class", "del", "dev", &ppp_iface, "classid", &format!("1:{down_min}")]).output();
    // P2: limpiar TAMBIEN el filtro UP en ifb_pppN y ELIMINAR el ifb
    // (leak — antes el ifb_pppN quedaba para siempre)
    let ifb = format!("ifb_{}", ppp_iface);
    let up_prio = format!("{}", 100 + (up_min - 1000) / 2);
    let _ = Command::new("tc").args(["filter", "del", "dev", &ifb, "parent", "1:0", "protocol", "ip", "prio", &up_prio,
        "u32", "match", "ip", "src", &client_ip, "flowid", &format!("1:{up_min}")]).output();
    let _ = Command::new("tc").args(["class", "del", "dev", &ifb, "classid", &format!("1:{up_min}")]).output();
    let _ = Command::new("ip").args(["link", "del", "dev", &ifb]).output();
    eprintln!("[PPP-CLEANUP] {}@{} limpiado (ifb {} eliminado)", client_ip, ppp_iface, ifb);
    Json(serde_json::json!({"ok": true, "cleanup": "done", "ifb": ifb}))
}

fn hex_to_bytes(s: &str) -> Vec<u8> {
    let s: String = s.chars().filter(|c| c.is_ascii_hexdigit()).collect();
    let mut out = Vec::with_capacity(s.len() / 2);
    let bytes = s.as_bytes();
    let mut i = 0;
    while i + 1 < bytes.len() {
        if let (Some(h), Some(l)) = (hex_nibble(bytes[i]), hex_nibble(bytes[i + 1])) {
            out.push(h * 16 + l);
        }
        i += 2;
    }
    out
}

fn hex_nibble(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        b'A'..=b'F' => Some(b - b'A' + 10),
        _ => None,
    }
}

// ─── REMOTO — DNAT dinamico a cliente PPP ──────────────────

const REMOTE_IP_FILE: &str = "/tmp/zpot-remote.txt";
const REMOTE_PORT: u16 = 8082;

/// GET /api/ip/remote — IP actual del forwarding
pub async fn remote_get() -> Json<Value> {
    let ip = std::fs::read_to_string(REMOTE_IP_FILE).unwrap_or_default();
    Json(serde_json::json!({"ip": ip.trim(), "port": REMOTE_PORT}))
}

/// POST /api/ip/remote — actualiza la IP destino del DNAT
/// Acceso remoto generico: puerto 8082 del servidor -> <ip>:80 del cliente
/// (vale para IPs Hotspot eth3 192.168.10.x y PPPoE eth3.881 192.168.20.x).
/// SIN iifname: el DNAT aplica por cualquier interfaz (wg0 VPN, eth1 internet).
/// ip vacio = DESACTIVAR (borra las reglas nft y el archivo de estado).
pub async fn remote_set(Json(body): Json<HashMap<String, String>>) -> Result<Json<Value>, (StatusCode, String)> {
    let ip = body.get("ip").map(|s| s.trim().to_string()).unwrap_or_default();

    // Desactivar: eliminar reglas DNAT (8082 y 443) y estado
    if ip.is_empty() {
        cleanup_remote_rules();
        let _ = std::fs::remove_file(REMOTE_IP_FILE);
        return Ok(Json(serde_json::json!({"status": "ok", "ip": "", "port": REMOTE_PORT})));
    }

    // Validar formato IP basico
    let parts: Vec<&str> = ip.split('.').collect();
    if parts.len() != 4 || parts.iter().any(|p| p.parse::<u8>().is_err()) {
        return Err((StatusCode::BAD_REQUEST, "invalid IP format".into()));
    }
    // P1: restringir a rangos LOCALES del servidor (hotspot o PPPoE) —
    // antes aceptaba CUALQUIER IP (DNAT a internet = proxy abierto)
    let oct = parts[0].parse::<u8>().unwrap_or(0);
    let oct3 = parts[2].parse::<u8>().unwrap_or(0);
    if !(oct == 192 && parts[1] == "168" && (oct3 == 10 || oct3 == 20)) {
        return Err((StatusCode::BAD_REQUEST,
            "IP fuera de rango local (solo 192.168.10.x hotspot / 192.168.20.x PPPoE)".into()));
    }

    let dst = format!("{}:80", ip);
    let dst_https = format!("{}:443", ip);

    cleanup_remote_rules();

    // Agregar nueva regla DNAT con comentario.
    // FIX (2026-08-04): restringida a iifname { wg0, eth1 } (solo admin VPN +
    // internet). ANTES era `iifname != "lo"` -> el DNAT 443 capturaba TODO el
    // HTTPS forward de clientes PPPoE/LAN (los mandaba al panel del AP) y el
    // 8082 dejaba que cualquier cliente hotspot NO autenticado abriera el AP.
    let remote_port_str = REMOTE_PORT.to_string();
    let _ = Command::new("nft").args(["add", "rule", "inet", "hotspot", "prerouting",
        "iifname", "{ \"wg0\", \"eth1\" }", "tcp", "dport", &remote_port_str, "dnat", "ip", "to", &dst, "comment", "zpot-remote"]).output();
    // HTTPS: el panel del AP (Ubiquiti/Omada) responde 302 a https://<host>/
    // -> DNAT 443 -> <ip>:443 para que el redirect siga pasando por el servidor.
    // El cleanup (comment "zpot-remote") tambien borra esta regla (contiene el prefijo).
    let _ = Command::new("nft").args(["add", "rule", "inet", "hotspot", "prerouting",
        "iifname", "{ \"wg0\", \"eth1\" }", "tcp", "dport", "443", "dnat", "ip", "to", &dst_https, "comment", "zpot-remote-https"]).output();

    // Guardar IP actual
    let _ = std::fs::write(REMOTE_IP_FILE, ip.as_bytes());

    Ok(Json(serde_json::json!({"status": "ok", "ip": ip, "port": REMOTE_PORT})))
}

/// Borra TODAS las reglas DNAT del acceso remoto (comment zpot-remote*)
/// de la chain prerouting de la tabla hotspot.
fn cleanup_remote_rules() {
    let list_out = Command::new("nft").args(["-a", "list", "chain", "inet", "hotspot", "prerouting"]).output()
        .map(|o| String::from_utf8_lossy(&o.stdout).to_string()).unwrap_or_default();
    for line in list_out.lines() {
        if line.contains("zpot-remote") {
            // Extraer handle: "handle N" al final de la linea
            if let Some(h) = line.split_whitespace().filter_map(|w| {
                if w.starts_with("handle") { w.strip_prefix("handle ") } else { None }
            }).last().or_else(|| {
                line.rsplit(' ').filter_map(|w| w.strip_prefix("handle ")).next()
            }).or_else(|| {
                // Buscar "handle" en la linea — el formato es ...comment "zpot-remote" # handle N
                line.split('#').nth(1).and_then(|s| s.trim().strip_prefix("handle "))
                    .or_else(|| line.rsplit("handle ").nth(1).and_then(|s| s.split_whitespace().next()))
            }) {
                if let Ok(handle) = h.parse::<u64>() {
                    let _ = Command::new("nft").args(["delete", "rule", "inet", "hotspot", "prerouting", "handle", &handle.to_string()]).output();
                }
            }
            // Tambien intentar con split por #
            for part in line.split('#') {
                let trimmed = part.trim();
                if let Some(hstr) = trimmed.strip_prefix("handle ") {
                    if let Ok(handle) = hstr.parse::<u64>() {
                        let _ = Command::new("nft").args(["delete", "rule", "inet", "hotspot", "prerouting", "handle", &handle.to_string()]).output();
                    }
                }
            }
        }
    }
}

// ─── SERVIDOR PPPoE — toggle ON/OFF ────────────────────────

const PPPOE_SERVER_BIN: &str = "/usr/sbin/pppoe-server";

/// GET /api/ppp/server/status — estado del pppoe-server (ON/OFF + PIDs)
/// OJO: BusyBox pgrep -x compara contra argv[0] COMPLETO ("/usr/sbin/pppoe-server"),
/// no contra comm -> no matchea. Usamos pgrep -f con patron [c]orchete para
/// evitar que el propio comando se encuentre a si mismo.
pub async fn pppoe_status() -> Json<Value> {
    let out = Command::new("/bin/sh")
        .args(["-c", "pgrep -f '[p]ppoe-server -I' || true"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default();
    let pids: Vec<&str> = out.split_whitespace().collect();
    Json(serde_json::json!({"running": !pids.is_empty(), "pids": pids}))
}

/// POST /api/ppp/server/start — arranca pppoe-server si no corre (idempotente)
pub async fn pppoe_start() -> Json<Value> {
    // P1: pool parametrizado desde ppp-radius.json (antes -R hardcodeado
    // 192.168.20.100 -N 100 — la UI pool_start/pool_end no se aplicaba)
    let mut args = String::from("-I eth4.881 -m 1412 -q /usr/sbin/pppd -L 192.168.20.1");
    let cfg = super::ppp_radius::load_config();
    let pool_start = cfg.pool_start.trim().to_string();
    let pool_end = cfg.pool_end.trim().to_string();
    let count = pool_start.parse::<u32>().ok()
        .zip(pool_end.parse::<u32>().ok())
        .map(|(s, e)| if e >= s { e - s + 1 } else { 0 })
        .unwrap_or(0);
    if count > 0 && !pool_start.is_empty() {
        args.push_str(&format!(" -R {} -N {}", pool_start, count));
    } else {
        args.push_str(" -R 192.168.20.100 -N 100");
    }
    let script = format!(
        "pgrep -f '[p]ppoe-server -I' >/dev/null || setsid {} {} >/dev/null 2>&1 &",
        PPPOE_SERVER_BIN, args
    );
    let _ = Command::new("/bin/sh").args(["-c", &script]).output();
    tokio::time::sleep(std::time::Duration::from_millis(300)).await;
    pppoe_status().await
}

/// POST /api/ppp/server/stop — detiene pppoe-server (impide nuevas conexiones)
/// Nota: las sesiones PPP activas quedan huérfanas hasta que el CPE reconecte.
pub async fn pppoe_stop() -> Json<Value> {
    let _ = Command::new("/bin/sh")
        .args(["-c", "pkill -f '[p]ppoe-server -I' || true"])
        .output();
    tokio::time::sleep(std::time::Duration::from_millis(300)).await;
    pppoe_status().await
}
